'use client'

import styles from './terms.module.css'

export default function TermsPage() {
  return (
    <div className={styles.container}>
      <div className={styles.landingBg}></div>
      <div className={styles.content}>
        <div className={styles.card}>
          <h1 className={styles.title}>Terms and Conditions</h1>
          <p className={styles.lastUpdated}>Last Updated: June 2025</p>
          
          <div className={styles.section}>
            <h2>1. Agreement to Terms</h2>
            <p>By accessing and using MudahPrompt ("the Service"), you agree to be bound by these Terms and Conditions ("Terms"). If you do not agree to these terms, please do not use our service. These Terms govern your use of our website, AI prompt generation services, and any content generated by our services.</p>
          </div>

          <div className={styles.section}>
            <h2>2. Privacy and Data Protection</h2>
            <p>Your privacy is important to us. Please review our Privacy Policy, which also governs your use of the Service, for information on how we collect, use, and share your information. By using our Service, you consent to the collection and use of your information as described in our Privacy Policy.</p>
          </div>

          <div className={styles.section}>
            <h2>3. Who May Use the Service</h2>
            <p>You may use the Service only if you are 18 years or older and capable of forming a binding contract. If you are accessing the Service on behalf of a company or other legal entity, you represent that you have the authority to bind that entity to these Terms.</p>
          </div>

          <div className={styles.section}>
            <h2>4. User Accounts</h2>
            <p>To access certain features, you must create an account. You agree to:</p>
            <ul>
              <li>Provide accurate, complete, and current information</li>
              <li>Maintain the security of your account credentials</li>
              <li>Notify us immediately of any unauthorized use</li>
              <li>Accept responsibility for all activities under your account</li>
            </ul>
          </div>

          <div className={styles.section}>
            <h2>5. Service Availability and Usage</h2>
            <p>MudahPrompt is currently provided as a free service supported by advertising revenue. We strive to maintain service availability but cannot guarantee uninterrupted access. We may modify, suspend, or discontinue the Service at any time with reasonable notice. We are not liable for any service interruptions.</p>
          </div>

          <div className={styles.section}>
            <h2>6. Advertising and Third-Party Services</h2>
            <p>Our Service is supported by Google AdSense advertising. By using our Service, you acknowledge that:</p>
            <ul>
              <li>Google AdSense may collect and process data for advertising purposes</li>
              <li>Third-party advertisers may use cookies and similar technologies</li>
              <li>You may see personalized advertisements based on your browsing behavior</li>
              <li>We are not responsible for the content or practices of third-party advertisers</li>
              <li>You can opt out of personalized advertising through your browser settings</li>
            </ul>
          </div>

          <div className={styles.section}>
            <h2>7. User Content and Generated Content</h2>
            <p><strong>User Content:</strong> You retain ownership of content you submit to the Service. By submitting content, you grant us a license to use, store, and process your content to provide the Service.</p>
            <p><strong>Generated Content:</strong> Content generated by our AI services is provided for your use. You are responsible for ensuring your use of generated content complies with applicable laws and these Terms.</p>
          </div>

          <div className={styles.section}>
            <h2>8. Acceptable Use Policy</h2>
            <p>You agree not to use the Service to:</p>
            <ul>
              <li>Violate any applicable laws or regulations</li>
              <li>Generate content that is illegal, harmful, or offensive</li>
              <li>Infringe on intellectual property rights</li>
              <li>Attempt to reverse engineer or hack the Service</li>
              <li>Use the Service for spam or unauthorized commercial purposes</li>
              <li>Share account credentials with others</li>
              <li>Generate content that promotes discrimination, violence, or illegal activities</li>
              <li>Block or interfere with advertisements displayed on the Service</li>
              <li>Use ad-blocking software that prevents the display of advertisements</li>
            </ul>
          </div>

          <div className={styles.section}>
            <h2>9. Intellectual Property Rights</h2>
            <p>MudahPrompt and its licensors own all rights to the Service, including software, design, and content. You retain rights to your user content, but we maintain rights to improve our services based on usage patterns.</p>
          </div>

          <div className={styles.section}>
            <h2>10. Limitation of Liability</h2>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, MUDHAPROMPT SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, OR BUSINESS OPPORTUNITIES. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT OF RM100 (ONE HUNDRED RINGGIT MALAYSIA).</p>
          </div>

          <div className={styles.section}>
            <h2>11. Indemnification</h2>
            <p>You agree to indemnify and hold harmless MudahPrompt, its officers, directors, employees, and agents from any claims, damages, or expenses arising from your use of the Service or violation of these Terms.</p>
          </div>

          <div className={styles.section}>
            <h2>12. Termination</h2>
            <p>We may suspend or terminate your account at any time for violation of these Terms. You may cancel your account at any time. Upon termination, your right to use the Service ceases immediately, and we may delete your account data.</p>
          </div>

          <div className={styles.section}>
            <h2>13. Changes to Terms</h2>
            <p>We may update these Terms from time to time. We will notify you of material changes through email or in-app notifications. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
          </div>

          <div className={styles.section}>
            <h2>14. Governing Law and Dispute Resolution</h2>
            <p>These Terms are governed by the laws of Malaysia. Any disputes shall be resolved in the courts of Malaysia. We encourage you to contact us first to resolve any issues amicably.</p>
          </div>

          <div className={styles.section}>
            <h2>15. Severability</h2>
            <p>If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.</p>
          </div>

          <div className={styles.section}>
            <h2>16. Contact Information</h2>
            <p>If you have any questions about these Terms and Conditions, please contact us at:</p>
            <p className={styles.contact}>aautomate123@gmail.com</p>
            <p>For legal matters, please include "Legal Inquiry" in the subject line.</p>
          </div>
        </div>
      </div>
    </div>
  )
} 